---

- name: Update apt caches.
  command: apt-get update

- name: Upgrade installed packages.
  command: apt-get upgrade -y
  when: common_upgrade

- name: Set TZ config file
  template:
    src=timezone.j2
    dest=/etc/timezone
  register: tz_result

# TODO: Broken in Ubuntu 12.04 - use debconf to inject configuration
#- name: Common | Reconfigure TZ
#  command: dpkg-reconfigure tzdata
#  when: tz_result.changed

- name: Configure language packs
  shell: locale-gen fr_FR fr_FR.UTF-8 && dpkg-reconfigure locales

- name: Install 'python-apt' module
  command: apt-get install python-apt -y

- name: Install misc utils
  apt: pkg={{ item }} state=present
  with_items:
  - htop
  - curl
  - tmux
  - unzip
  - python-software-properties      # Dependencies for the apt module
  - software-properties-common
  - python-pycurl
  - vim

- name: Push global vimrc
  template:
    src=vimrc.j2
    dest=/etc/vim/vimrc.local

- name: Set vim as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic

