- name: "Install the distribution's Ruby base packages"
  apt: pkg={{ item }} state=installed
  with_items:
  - ruby
  - rubygems
  - libxml2   # nokogiri needs this, and most applications use nokogiri

# Put this in an extra file, and load a gem's dependencies before the gem itself.
- name: Install gems
  gem: name={{ item }} state=latest
  with_items: ruby_gems


